// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: v1/control.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Connect_FullMethodName = "/superebpf.v1.ControlPlane/Connect"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane is the service that users implement on their control plane
// server. The daemon connects to this service and maintains a bidirectional
// stream.
type ControlPlaneClient interface {
	// Connect establishes a bidirectional stream between the daemon and control
	// plane.
	//
	// Flow:
	// 1. Daemon connects and sends SyncRequest with current attachments
	// 2. Control plane sends SyncAck
	// 3. Daemon sends Subscribed when local orchestration attaches filters
	// 4. Control plane sends filter commands (AllowCIDR, SetMode, etc.)
	// 5. Daemon sends Unsubscribed when attachments are detached/removed
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonEvent, ControlCommand], error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonEvent, ControlCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DaemonEvent, ControlCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_ConnectClient = grpc.BidiStreamingClient[DaemonEvent, ControlCommand]

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane is the service that users implement on their control plane
// server. The daemon connects to this service and maintains a bidirectional
// stream.
type ControlPlaneServer interface {
	// Connect establishes a bidirectional stream between the daemon and control
	// plane.
	//
	// Flow:
	// 1. Daemon connects and sends SyncRequest with current attachments
	// 2. Control plane sends SyncAck
	// 3. Daemon sends Subscribed when local orchestration attaches filters
	// 4. Control plane sends filter commands (AllowCIDR, SetMode, etc.)
	// 5. Daemon sends Unsubscribed when attachments are detached/removed
	Connect(grpc.BidiStreamingServer[DaemonEvent, ControlCommand]) error
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Connect(grpc.BidiStreamingServer[DaemonEvent, ControlCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServer).Connect(&grpc.GenericServerStream[DaemonEvent, ControlCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_ConnectServer = grpc.BidiStreamingServer[DaemonEvent, ControlCommand]

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "superebpf.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ControlPlane_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1/control.proto",
}
