// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/types.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyMode defines the filtering behavior.
type PolicyMode int32

const (
	PolicyMode_POLICY_MODE_UNSPECIFIED PolicyMode = 0
	// Disabled - all traffic allowed, filter is a no-op
	PolicyMode_POLICY_MODE_DISABLED PolicyMode = 1
	// Allowlist - only allow traffic to IPs in the allowlist, block all else
	PolicyMode_POLICY_MODE_ALLOWLIST PolicyMode = 2
	// Block all - block all outbound traffic
	PolicyMode_POLICY_MODE_BLOCK_ALL PolicyMode = 3
	// Denylist - block traffic to IPs in the denylist, allow all else
	PolicyMode_POLICY_MODE_DENYLIST PolicyMode = 4
)

// Enum value maps for PolicyMode.
var (
	PolicyMode_name = map[int32]string{
		0: "POLICY_MODE_UNSPECIFIED",
		1: "POLICY_MODE_DISABLED",
		2: "POLICY_MODE_ALLOWLIST",
		3: "POLICY_MODE_BLOCK_ALL",
		4: "POLICY_MODE_DENYLIST",
	}
	PolicyMode_value = map[string]int32{
		"POLICY_MODE_UNSPECIFIED": 0,
		"POLICY_MODE_DISABLED":    1,
		"POLICY_MODE_ALLOWLIST":   2,
		"POLICY_MODE_BLOCK_ALL":   3,
		"POLICY_MODE_DENYLIST":    4,
	}
)

func (x PolicyMode) Enum() *PolicyMode {
	p := new(PolicyMode)
	*p = x
	return p
}

func (x PolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_types_proto_enumTypes[0].Descriptor()
}

func (PolicyMode) Type() protoreflect.EnumType {
	return &file_v1_types_proto_enumTypes[0]
}

func (x PolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyMode.Descriptor instead.
func (PolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_v1_types_proto_rawDescGZIP(), []int{0}
}

// AttachmentType indicates how the filter is attached.
type AttachmentType int32

const (
	AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED AttachmentType = 0
	AttachmentType_ATTACHMENT_TYPE_TC          AttachmentType = 1
	AttachmentType_ATTACHMENT_TYPE_CGROUP      AttachmentType = 2
)

// Enum value maps for AttachmentType.
var (
	AttachmentType_name = map[int32]string{
		0: "ATTACHMENT_TYPE_UNSPECIFIED",
		1: "ATTACHMENT_TYPE_TC",
		2: "ATTACHMENT_TYPE_CGROUP",
	}
	AttachmentType_value = map[string]int32{
		"ATTACHMENT_TYPE_UNSPECIFIED": 0,
		"ATTACHMENT_TYPE_TC":          1,
		"ATTACHMENT_TYPE_CGROUP":      2,
	}
)

func (x AttachmentType) Enum() *AttachmentType {
	p := new(AttachmentType)
	*p = x
	return p
}

func (x AttachmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_types_proto_enumTypes[1].Descriptor()
}

func (AttachmentType) Type() protoreflect.EnumType {
	return &file_v1_types_proto_enumTypes[1]
}

func (x AttachmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentType.Descriptor instead.
func (AttachmentType) EnumDescriptor() ([]byte, []int) {
	return file_v1_types_proto_rawDescGZIP(), []int{1}
}

// TcDirection selects which TCX hook a TC (interface) filter attaches to.
// It is only meaningful for interface targets; for cgroup targets it is
// ignored (cgroup filters hook socket operations, not an interface).
//
// Picking the correct direction depends on which side of the link the
// interface is on:
//   - EGRESS is correct when the interface transmits the workload's outbound
//     traffic: an uplink like eth0, or an interface inside the workload's own
//     network namespace. There the packet's destination address is the true
//     external destination.
//   - INGRESS is correct for host-side veth peers and VM tap devices (e.g.
//     "fcr-*"). The workload's outbound traffic arrives at the host ON that
//     interface (ingress); attaching egress there would instead see
//     host-to-workload return traffic and filter by the workload's own
//     address rather than the true destination.
type TcDirection int32

const (
	// Treated as TC_DIRECTION_EGRESS (preserves pre-direction behavior).
	TcDirection_TC_DIRECTION_UNSPECIFIED TcDirection = 0
	// Filter packets transmitted out through the interface.
	TcDirection_TC_DIRECTION_EGRESS TcDirection = 1
	// Filter packets received by the host from the interface.
	TcDirection_TC_DIRECTION_INGRESS TcDirection = 2
)

// Enum value maps for TcDirection.
var (
	TcDirection_name = map[int32]string{
		0: "TC_DIRECTION_UNSPECIFIED",
		1: "TC_DIRECTION_EGRESS",
		2: "TC_DIRECTION_INGRESS",
	}
	TcDirection_value = map[string]int32{
		"TC_DIRECTION_UNSPECIFIED": 0,
		"TC_DIRECTION_EGRESS":      1,
		"TC_DIRECTION_INGRESS":     2,
	}
)

func (x TcDirection) Enum() *TcDirection {
	p := new(TcDirection)
	*p = x
	return p
}

func (x TcDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TcDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_types_proto_enumTypes[2].Descriptor()
}

func (TcDirection) Type() protoreflect.EnumType {
	return &file_v1_types_proto_enumTypes[2]
}

func (x TcDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TcDirection.Descriptor instead.
func (TcDirection) EnumDescriptor() ([]byte, []int) {
	return file_v1_types_proto_rawDescGZIP(), []int{2}
}

// DnsMode defines the DNS filtering behavior.
type DnsMode int32

const (
	DnsMode_DNS_MODE_UNSPECIFIED DnsMode = 0
	// Disabled - no DNS interception, pure IP filtering
	DnsMode_DNS_MODE_DISABLED DnsMode = 1
	// Allowlist - only resolve allowed domains, block all else
	DnsMode_DNS_MODE_ALLOWLIST DnsMode = 2
	// Denylist - block denied domains, allow all else
	DnsMode_DNS_MODE_DENYLIST DnsMode = 3
	// Proxy - forward all queries to control plane for decision
	DnsMode_DNS_MODE_PROXY DnsMode = 4
)

// Enum value maps for DnsMode.
var (
	DnsMode_name = map[int32]string{
		0: "DNS_MODE_UNSPECIFIED",
		1: "DNS_MODE_DISABLED",
		2: "DNS_MODE_ALLOWLIST",
		3: "DNS_MODE_DENYLIST",
		4: "DNS_MODE_PROXY",
	}
	DnsMode_value = map[string]int32{
		"DNS_MODE_UNSPECIFIED": 0,
		"DNS_MODE_DISABLED":    1,
		"DNS_MODE_ALLOWLIST":   2,
		"DNS_MODE_DENYLIST":    3,
		"DNS_MODE_PROXY":       4,
	}
)

func (x DnsMode) Enum() *DnsMode {
	p := new(DnsMode)
	*p = x
	return p
}

func (x DnsMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DnsMode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_types_proto_enumTypes[3].Descriptor()
}

func (DnsMode) Type() protoreflect.EnumType {
	return &file_v1_types_proto_enumTypes[3]
}

func (x DnsMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DnsMode.Descriptor instead.
func (DnsMode) EnumDescriptor() ([]byte, []int) {
	return file_v1_types_proto_rawDescGZIP(), []int{3}
}

var File_v1_types_proto protoreflect.FileDescriptor

const file_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/types.proto\x12\vnetfence.v1*\x93\x01\n" +
	"\n" +
	"PolicyMode\x12\x1b\n" +
	"\x17POLICY_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14POLICY_MODE_DISABLED\x10\x01\x12\x19\n" +
	"\x15POLICY_MODE_ALLOWLIST\x10\x02\x12\x19\n" +
	"\x15POLICY_MODE_BLOCK_ALL\x10\x03\x12\x18\n" +
	"\x14POLICY_MODE_DENYLIST\x10\x04*e\n" +
	"\x0eAttachmentType\x12\x1f\n" +
	"\x1bATTACHMENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ATTACHMENT_TYPE_TC\x10\x01\x12\x1a\n" +
	"\x16ATTACHMENT_TYPE_CGROUP\x10\x02*^\n" +
	"\vTcDirection\x12\x1c\n" +
	"\x18TC_DIRECTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TC_DIRECTION_EGRESS\x10\x01\x12\x18\n" +
	"\x14TC_DIRECTION_INGRESS\x10\x02*}\n" +
	"\aDnsMode\x12\x18\n" +
	"\x14DNS_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DNS_MODE_DISABLED\x10\x01\x12\x16\n" +
	"\x12DNS_MODE_ALLOWLIST\x10\x02\x12\x15\n" +
	"\x11DNS_MODE_DENYLIST\x10\x03\x12\x12\n" +
	"\x0eDNS_MODE_PROXY\x10\x04B1Z/github.com/danthegoodman1/netfence/api/v1;apiv1b\x06proto3"

var (
	file_v1_types_proto_rawDescOnce sync.Once
	file_v1_types_proto_rawDescData []byte
)

func file_v1_types_proto_rawDescGZIP() []byte {
	file_v1_types_proto_rawDescOnce.Do(func() {
		file_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_types_proto_rawDesc), len(file_v1_types_proto_rawDesc)))
	})
	return file_v1_types_proto_rawDescData
}

var file_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1_types_proto_goTypes = []any{
	(PolicyMode)(0),     // 0: netfence.v1.PolicyMode
	(AttachmentType)(0), // 1: netfence.v1.AttachmentType
	(TcDirection)(0),    // 2: netfence.v1.TcDirection
	(DnsMode)(0),        // 3: netfence.v1.DnsMode
}
var file_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_types_proto_init() }
func file_v1_types_proto_init() {
	if File_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_types_proto_rawDesc), len(file_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_types_proto_goTypes,
		DependencyIndexes: file_v1_types_proto_depIdxs,
		EnumInfos:         file_v1_types_proto_enumTypes,
	}.Build()
	File_v1_types_proto = out.File
	file_v1_types_proto_goTypes = nil
	file_v1_types_proto_depIdxs = nil
}
